apiVersion: apps/v1
kind: Deployment
metadata:
  name: kind-autoscaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kind-autoscaling
  template:
    metadata:
      labels:
        app: kind-autoscaling
    spec:
      containers:
      - name: kind-autoscaling
        image: avis22/java-app:1.0
        ports:
           - containerPort: 8280
    
      imagePullSecrets:
           - name: regcred


