apiVersion: v1
kind: Service
metadata:
  name: kind-autoscaling
spec:
  selector:
    app: kind-autoscaling  # This must match the label in your Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8280
      nodePort: 30002  # Optional: needed if you're mapping hostPort in kind-config.yaml
  type: NodePort

