apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  selector:
    app: java-app  # This must match the label in your Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # Optional: needed if you're mapping hostPort in kind-config.yaml
  type: NodePort

