apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: avis22/java-app:1.0
        ports:
           - containerPort: 8080
      imagePullSecrets:
           - name: regcred

